server:
  port: 8080
  servlet:
    context-path: /cctv-core

spring:
  application:
    name: cctv-core

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: '${KC_URI:http://localhost:8081/realms/smart-cctv}'

  data:
    mongodb:
      uri: '${MONGODB_URI:mongodb://localhost:27017/smart_cctv?directConnection=true}'
    redis:
      host: '${REDIS_HOST:localhost}'
      port: '${REDIS_PORT:6379}'
  rabbitmq:
    host: '${RABBITMQ_HOST:localhost}'
    port: '${RABBITMQ_PORT:5672}'
    username: '${RABBITMQ_USERNAME:admin}'
    password: '${RABBITMQ_PASSWORD:admin}'
    virtual-host: '${RABBITMQ_VHOST:/}'

messaging:
  provider: '${MESSAGING_PROVIDER:rabbitmq}'

redis:
  channels:
    intrusion-events: '${REDIS_CHANNEL_INTRUSION:intrusion_alerts}'
    modify-cctv: '${REDIS_CHANNEL_MODIFY:modify_zone_cctv}'

rabbitmq:
  exchange: '${RABBITMQ_EXCHANGE:cctv_events}'
  queues:
    intrusion-events: '${RABBITMQ_QUEUE_INTRUSION:intrusion_alerts}'
    modify-cctv: '${RABBITMQ_QUEUE_MODIFY:modify_zone_cctv}'
  routing-keys:
    intrusion-events: '${RABBITMQ_RK_INTRUSION:intrusion_alerts}'
    modify-cctv: '${RABBITMQ_RK_MODIFY:modify_zone_cctv}'

idp:
  realm: '${KC_REALM:smart-cctv}'
  url: '${KC_URL:http://localhost:8081}'
  client-id: '${KC_CLIENT_ID:cctv-core}'
  client-secret: '${KC_CLIENT_SECRET:}'

stream:
  app:
    base:
      url: '${GO2RTC_URL:localhost:1984}'

cloud-storage:
  r2:
    account-id: '${R2_ACCOUNT_ID}'
    access-key: '${R2_ACCESS_KEY}'
    secret-key: '${R2_SECRET_KEY}'
    bucket-name: '${R2_BUCKET_NAME:smart-cctv}'
    public-url: '${R2_PUBLIC_URL}'

camera:
  health-check:
    interval-ms: '${CAMERA_HEALTH_INTERVAL_MS:60000}'

app:
  storage:
    type: '${STORAGE_TYPE:local}'
    base-url: '${STORAGE_BASE_URL:http://localhost:8080/cctv-core/snapshots}'
  snapshot:
    dir: '${SNAPSHOT_DIR:./snapshots}'
