server:
  port: 8080
  servlet:
    context-path: /cctv-core

spring:
  application:
    name: cctv-core

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/cctv
  data:
    mongodb:
      uri:
    redis:
      host: localhost
      port: 6379

redis:
  channels:
    intrusion-events: cctv:intrusion:events
    modify-cctv: cctv:modify:events

idp:
  realm: cctv
  url: http://localhost:8180
  client-id:
  client-secret: